### ISSUE TITLE
Cannot use many common versions: ESV, NASB, NKJV

### ISSUE THREAD

**Issue by bspivey** [avendesora/pythonbible#149]
I receive the following error when using many common English versions.

MissingBookFileError: <Version.ENGLISH_STANDARD: 'ESV'>

**Comment by avendesora** [comment]
Hi!

We only include the actual content for two versions currently: ASV and KJV. We plan to eventually support all public domain and open source versions, but we will never include non public domain / open source versions in the core library. You will need to obtain permission from the relevant publisher for that version as well as the actual content and incorporate that into your application. We do plan to eventually make it easier to "bring your own" versions, which is why we added the enum values for more versions than we currently support, and I'll let you know as we make progress on that work.

Ultimately, though, as an open source project we can't include any content that requires a non open source license.

Thanks,
Nathan
