### ISSUE TITLE
pythonbible package exceed memory(Process running mem=660M(129.0%)) usage on Heroku server

### ISSUE THREAD

**Issue by williams9438** [avendesora/pythonbible#33]
Process running mem=660M(129.0%) when using this package on heroku

**Comment by williams9438** [comment]
How can i resolve this issue?

**Comment by avendesora** [comment]
Can you provide a code example that causes this memory issue? Thanks.

**Comment by avendesora** [comment]
My guess is that it is due to overly aggressive caching within the pythonbible library. We need to do some real profiling to determine what the optimal max size of the cache ought to be. Currently, it is set to None, which means that the cache can grow indefinitely. For a quick fix, I'm going to change that to be the default max size (128 entries, I think), and will release that change shortly. For a long-term fix, I'll create a project to determine the optimal max size of the cache based on profiling exercises as well as possibly allowing for configurable cache settings.

**Comment by avendesora** [comment]
I have released a hotfix that might help with this issue. Please upgrade to the latest version of pythonbible and try it out and let me know whether or not it resolves your specific issue. You can upgrade to the latest version by running either:

pip install -U pythonbible

or

pip install pythonbible==0.4.1

Thanks.

**Comment by williams9438** [comment]
> My guess is that it is due to overly aggressive caching within the pythonbible library. We need to do some real profiling to determine what the optimal max size of the cache ought to be. Currently, it is set to None, which means that the cache can grow indefinitely. For a quick fix, I'm going to change that to be the default max size (128 entries, I think), and will release that change shortly. For a long-term fix, I'll create a project to determine the optimal max size of the cache based on profiling exercises as well as possibly allowing for configurable cache settings.

Yes
